name: Deploy Hotel Booking App

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Build Docker image
      run: docker build -t hotel-booking .
    
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: "dummy"
    
    - name: Deploy to EC2
      run: |
        docker save hotel-booking -o hotel-booking.tar
        scp -o StrictHostKeyChecking=no hotel-booking.tar ec2-user@${{ secrets.EC2_HOST }}:~
        ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} "
          docker load -i ~/hotel-booking.tar
          docker stop hotel-app || true
          docker rm hotel-app || true
          docker run -d --name hotel-app -p 5000:5000 hotel-booking
        "
